_BASE_: "Base-RCNN-FPN.yaml"
TRAINER: "VideoTrainer"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  EMBED_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "ExtendedROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 8
  ROI_EMBED_HEAD:
    NAME: "QuasiDenseEmbedHead"
  TRACKER:
    NAME: "QuasiDenseTracker"
DATALOADER:
  SAMPLER_TRAIN: "VideoTrainingSampler"
DATASETS:
  TRAIN: ("bdd100k_mot_train", "bdd100k_det_mot_train",) # train 278079 + 69863
  TEST: ("bdd100k_mot_val",)  # val 39973
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (175000, 240000)
  MAX_ITER: 261000
INPUT:
  NUM_FRAMES_TRAIN: 2
  MIN_SIZE_TRAIN: (720,)
  MAX_SIZE_TRAIN: 1280
  MIN_SIZE_TEST: 720
  MAX_SIZE_TEST: 1280
